# Generated by Django 2.0.4 on 2018-04-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('people', models.IntegerField(null=True)),
                ('date', models.DateTimeField(max_length=12, null=True)),
            ],
            options={
                'db_table': 'website_contact_database',
                'managed': True,
            },
        ),
    ]
