# Generated by Django 2.0.4 on 2018-04-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzahut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='message',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
